<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>eef602c9-d15d-4f62-a4ad-99486a3de91e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Memory.Api\Memory.Api.csproj" IsAspireProjectResource="true" />
  </ItemGroup>

</Project>
